nghttp2/nghttp2

.travis.yml
and it is now valided by http://lint.travis-ci.org/
(Hooray, your .travis.yml seems to be solid!)
=> Travis: Remove python (No needed)

lib/nghttp2_hd_huffman.c
=> Fix other shorten-64-to-32 casting error found by MSVC (64bits)

src/HttpServer.cc, src/HttpServer.h, src/nghttp.cc, src/nghttpd.cc, src/util.cc, src/util.h
This change adds a `-a` parameter that can be used to select the IP address that the http server will bind to.  During testing I used this option to use multiple http servers on the same machine each with different addresses.  The parameter is optional and if not specified then the server binds to the default address returned from `getaddrinfo`.  This option is available in other http servers such as node's `http-server`.  I also added some additional logic to the print statement so that the address is printed along with the port.
Note I was having some trouble with getting clang-format to work correctly on Ubuntu so I had to edit the formatting manually.  I think it is pretty close to the style that you have setup but let me know if there are any formatting changes that need to be …
=> Adding address option to select the address to bind to

src/nghttp.cc
fixes #177 
Apparently this issues relates to https://github.com/tatsuhiro-t/nghttp2/issues/161
=> do not send pseudo-headers when in HTTP/1

lib/includes/nghttp2/nghttp2.h
... since gcc -pedantic warns on it.
=> nghttp2.h: remove trailing comma last in enum

src/h2load.cc
Thanks for the hint, this works on my system correctly so far.
=> fix for segfault by reserving correct worker count

README.rst
OpenSSL 1.0.2 is already released. Avoid the confusing wording that
seems to suggest that a development version of OpenSSL 1.0.2 provides
ALPN support.
=> README.rst: OpenSSL 1.0.2 has already been released

lib/nghttp2_net.h
"static inline" doesn't build on VS2013:
https://msdn.microsoft.com/en-us/library/z8y1yy88.aspx
=> "static inline" fix for build with VS2013

src/h2load.cc, src/h2load.h
I was doing some SPDY & HTTP2 performance testing w/ h2load and wanted to also get connect time and time to first byte statistics, so I added them. 
Opening a PR in case this is code that others might want. Let me know what you think of my implementation or if you would like me to make any changes.
=> update h2load to give connect time and ttfb stats

src/h2load_spdy_session.cc
Compilation error around errno when building with Dockerfile.android
=> h2load_spdy_session errno include

contrib/nghttpx-logrotate
I assume this logrotate configuration file is for Apache Web Server in Debian / Ubuntu? Here are some improvements to make it more universal:
- Avoid changing file permissions
- Make sure all log files are reopened
- Remove non-sense prerotate script
- Send SIGUSR1 to all nghttpx processes
=> Improve logrotate configuration file

contrib/nghttpx-upstart.conf
Upstart is used in Ubuntu 6.10 -> Ubuntu 14.10 as the default init daemon.
Starting with Ubuntu 15.04, Ubuntu switched to systemd.
Ubuntu Server LTS releases (12.04 and 14.04) are still using Upstart as their default init daemon.
This is the Upstart configuration file for those releases. :-)
=> Add Upstart configuration file

lib/nghttp2_hd.c
The assert only evaluates to code if NDEBUG is undefined. Protect rv and its use accordingly
Issue reported by Joerg Mayer
https://code.wireshark.org/review/8260
=> rv is only used in an assert.

lib/nghttp2_buf.c
When adding a large amount of data that spans to multiple chunks, the pointer is incremented by the wrong value.
=> Access violation in buffers

python/nghttp2.pyx
Setting TCP_NODELAY may fail. Instead of failing the routine, log it and continue.
It seems, that setting TCP_NODELAY in python on Mac OS X is not necessarily supported.
=> Catch and log failure to set TCP_NODELAY

configure.ac
The == operator is not in POSIX; use = like normal.
Reported-by: Mikael Magnusson <mikachu@gmail.com>
=> configure: fix bashism

configure.ac
Since this library uses the third-party subdir, make sure we auto-enable
it when that lib is turned on.
=> enable third-party for asio_lib too

src/h2load.cc, src/h2load.h
I would like to add the ability to specify a constant test time for h2load. In order to specify a constant time, I have added two new options: one to specify the rate at which connections are made, and another to specify the total number of connections to be made throughout the test. 
Feature 1 -- connection rate
------
The new rate option for h2load will allow users to specify the number of connections made per second.
-r, --rate=N
Specifies the fixed rate at which connections are created. The rate must be a positive integer, representing the number of connections to be made per second. When the rate is 0, the program will run as it normally does, creating connections at whatever variable rate it wants. The default value for this option is 0. To use the -r option, the -T option and …
=> h2load add rate and num connections options

gennghttpxfun.py, src/shrpx-unittest.cc, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_config_test.cc, src/shrpx_config_test.h, src/shrpx_ssl.cc, src/util.h
This PR adds AES-256-CBC cipher to encrypt TLS session ticket.
For this purpose, we added --tls-ticket-cipher option.  The available values are aes-128-cbc (this is default), and aes-256-cbc.
Since we used the same file format with nginx and apache, we used 16 bytes key for HMAC SHA-256.
It seems this is not a big problem today, but we have not figured out the reason why 16 bytes are used.
So this PR attempts to fix this.  When --tls-ticket-key-file is not used, we now use 32 bytes for HMAC key,as suggested in RFC 5077.  When --tls-ticket-key-file is used, and aes-128-cbc is given in new --tls-ticket-cipher option, 16 bytes HMAC key is used for backward compatibility.  On the other hand, with file and aes-256-cbc in --tls-ticket-cipher, full 32 bytes HMAC key is used.
=> nghttpx: Add AES-256-CBC encryption for TLS session ticket

doc/sources/tutorial-server.rst
The overall meaning of the tutorial is the same, except for a couple of changes:
- app_context struct was called "app_content", fixed the typo
- nghttp2_session_server_new2() is mentioned, but the example uses nghttp2_session_server_new() instead, changed the text to match
I've made the tutorial text a tiny bit easier to read. If this is useful I could help make similar improvements to the client tutorial and the main API reference.
=> doc: Reword some of the server tutorial.

doc/sources/tutorial-hpack.rst
The overall meaning is the same. I added a paragraph to introduce nghttp2_hd_inflate_hd(), and added an explanation of using NGHTTP2_NV_FLAG_NO_INDEX for security sensitive headers.
=> doc: Reword the HPAC tutorial.

src/h2load.cc
Continuing #324 as single commit.
=> h2load allow -r < -n when -n is not specified 

doc/h2load.h2r, src/h2load.cc, src/h2load.h
Continuing #322. 
It would be nice if h2load could timeout certain connections and close them, rather than waiting indefinitely until they close by themselves. In order to do this, I would like to add two new options to h2load: one to specify a way to timeout a connection after a fixed period of time, and another to timeout a connection if there has been no activity on said connection for a fixed period of time. 
Option 1 -- active timeout
========
This new option for h2load will ensure that all connections have a max time they are allowed to be open.
-T, --connection-active-timeout=N
Specifies the maximum time that h2load is willing to keep a connection open, regardless of the activity on said connection. N must be a positive integer, specifying the number of seconds to wait. When no …
=> h2load timeout options

src/h2load.cc, src/h2load.h
Hi Tatsuhurio,
This pull request adds two features to h2load:
1) A new timing script file to allow h2load to issue requests according to a script. A copy of the script is executed by all clients. The file format is tab-separated, field one defines the time to execute the request, measured from the start in milliseconds to microsecond resolution. Field two defines the URI. A new command-line parameter is added to h2load to define the use of this file. The number of requests is contrained to the length of the file, it doesn't seem logical to loop back to start of script.
Example file format
```
100.0	https://localhost/index.html
200.0	/style.css
300	/script.js
```
2) A base URI can be defined in a new command-line parameter. This is used to define the scheme, host and port number to be used …
=> Add Timing-script and base URI support

src/shrpx.cc, src/shrpx_log.cc, src/util.cc, src/util.h
This seems to do the trick for the issue #325.
It may also be used to simplify the Android-specific workarounds with /proc/self/df/2.
=> Map /dev/stdout and /dev/stderr to their descriptors.

README.rst
Hello everyone,
Will you guys mind adding `#include <iostream>` to the `nghttp2_asio` server example in `README.rst` to make it consistent with the client example?
With this included people can just copy and paste the code and compile them without any error.
Best,
Dash
=> Adding `iostream` to the example code snippet of nghttp2_asio sever

contrib/nghttpx-init.in
This is a short fix for the bug in sysv service (see https://bugs.debian.org/798598).
nghttpx should be started with --daemon
Cheers,
Tomasz
=> start nghttpx with --daemon

src/shrpx_ssl.cc
This silences warning log that otherwise spams logs on every accepted
connection.
=> Do not try to set TCP_NODELAY when frontend is an UNIX socket

contrib/nghttpx-init.in
Instead of assuming that upgrade is always successful, check if a new
process actually started. Do not kill old process if the new one
failed.
=> Make traditional init script fail if new config file is broken

contrib/nghttpx.service.in
Systemd assumes that service of type simple is stopped when the main
process exits. This causes systemd to kill all nghttpx processes when
doing a process upgrade (via USR2/QUIT signals). Change the service
type to forking which behaves correctly on upgrade.
=> Fix daemon upgrade when running under systemd

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h
This patch enables setting fastopen on listening tcp socket to allow faster connection setup. 
--fastopen option was added to binary which will take limit of number of requests with handshake for security.
More description https://tools.ietf.org/html/rfc7413
=> Added support for RFC 7413 (TCP Fast Open) on nghttpx proxy for listening connections.

src/h2load.cc, src/h2load.h
This PR relates to #358. The changes take a different approach from my initial suggestion in the issue, its a quick prototype rather than the finished goods but I've done some testing and looks ok so far.
A new option `--rate-period` is added allowing a user to define a period between client creation greater than 1 second (the default is still 1 second so existing functionality is unaffected). This allows a user to define that a total `C` clients should be created at a rate of `rate / rate-period`. 
The effect of combining these parameters may not be immediately obvious to a user, therefore some more information is printed at startup. Most importantly clients may not be concurrent when using rate mode, so we remove that terminology.
Note that this PR does not address the `connection rate …
=> h2load: Add option for user-definable rate period

doc/sources/nghttpx-howto.rst
Chromium's support for HTTP/2 proxy has been fixed in v46 (https://github.com/tatsuhiro-t/nghttp2/issues/151). Recently, Google Chrome v46 (stable channel) has been released. It's okay to update the doc to indicate that Chromium (stable version) now supports HTTP/2 proxy. (I have confirmed that myself)
=> Update doc for Chromium HTTP/2 proxy support

src/h2load.cc
Fixes bug introduced in b051dde as part of #411
=> h2load: do not overwrite protocol value

contrib/usr.sbin.nghttpx
Hi,
I propose to add an apparmor profile for nghttpx. This is my first take, it seems to work, although it assumes that the SSL keys are stored under /etc/ssl/. I plan to add this in the Debian package, but before that I wanted to discuss this with you.
Let me know what you think!
Cheers,
Tomasz
=> added apparmor profile

doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_priority_spec.c, lib/nghttp2_priority_spec.h, lib/nghttp2_session.c, lib/nghttp2_submit.c, tests/main.c, tests/nghttp2_session_test.c, tests/nghttp2_session_test.h
The added API is nghttp2_session_change_stream_priority().  This
provides the same functionality to re-prioritize stream when PRIORITY
frame.  is received, but we do it without PRIORITY frame.  This could
be useful for server to change pushed stream's priority silently.
=> Add API to change stream priority without sending PRIORITY frame

src/asio_io_service_pool.cc, src/asio_io_service_pool.h, src/asio_server.cc, src/asio_server.h, src/asio_server_http2.cc, src/asio_server_http2_impl.cc, src/asio_server_http2_impl.h, src/includes/nghttp2/asio_http2_server.h
To allow the asio wrapper to work with boost.fiber it is required
to access the underlying io_service objects.
=> libnghttp2_asio: Added io_service accessors

src/shrpx_config.cc
http header keys are case-insensitive, but header values are case-sensitive, so it should not be changed.
=> header value should not be inp_strlower

README.rst, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c
easy fix.
- heder -> header
- alreay -> already
- reponse -> response
=> fix typos in documents.

configure.ac
This makes linking fail on -ldl as there is no libdl on in /usr/lib or /usr/local/lib on *BSD
Tested (and part of the proposed nghttp2 1.7.0) on [https://reviews.freebsd.org/D5218|FreeBSD]
=> Don't check for dlopen/libdl on *BSD

README.rst, configure.ac, doc/sources/h2load-howto.rst
Finding the info on how to compile h2load was surprisingly hard -- it's got a documentation page on how to use it (https://nghttp2.org/documentation/h2load-howto.html) but compilation isn't mentioned and there's no mention in the configure file or readme.
This PR adds those details, highlighting that the ``--enable-app`` flag is what needs to be passed to `./configure` to build.
=> Document compiling apps and include h2load in configure

doc/Makefile.am, doc/conf.py.in, examples/client.c, examples/tiny-nghttpd.c, integration-tests/Makefile.am, integration-tests/config.go.in, integration-tests/server_tester.go, lib/nghttp2_npn.h
Fixes building docs (`make man`, `make latex`) in an out-of-tree build and running integration tests (`make it`). The cmake series depend on this for a proper out-of-tree build.
Also includes two minor fixes (compile warnings in examples and a harmless `HAVE_CONFIG(_H)` typo).
=> Improve support for out-of-tree builds, assorted build fixes

tests/nghttp2_session_test.c
Since v0.6.2-7-g1d138ac ("Unify DATA and other frames in
nghttp2_outbound_item and save malloc()"), the macros are unused and the
builds fails on -Werror=unused-macros.
=> tests: remove unused macros

.travis.yml, configure.ac, integration-tests/Makefile.am
This is a preparation for the CMake build system which does not have an "it-local" target. After this change you cannot invoke "make it" from the root directory (when using autotools), if that is wanted additional targets could be added to the top Makefile.am. (The documented `make -C integration-tests it` command is still functional though.)
___
Older automake (travis, *cough*) do not support the
AM_EXTRA_RECURSIVE_TARGETS option, this results in invoking "it-local"
directly in the travis script which relies on an implementation detail.
Since the "it" target is only used by the integration-tests directory,
just avoid the recursive targets. The README.rst suggests to enter the
integration-tests directory anyway.
=> integration-tests: do not use recursive target

src/nghttp.cc, src/nghttp.h
This patchset implements an `--expect-continue` option for `nghttp`. The intent is to make it easier to test Expect/Continue handshakes against HTTP/2 server implementations. (For context, see [the definition of the Expect header](https://tools.ietf.org/html/rfc7231#section-5.1.1) as well as the last example in [RFC 7540, Sec 8.1.3](https://tools.ietf.org/html/rfc7540#section-8.1.3).)
The new option only takes effect when uploading data with `-d`. To avoid having a nonconforming server hang the client indefinitely, the Expect/Continue mechanism times out after a short delay (currently hard-coded to one second).
The three patches are divided as follows:
1. add the `getopt_long()` parsing for the new option
2. implement the handshake logic itself
3. add a timeout for each request using …
=> nghttp: Implement an Expect/Continue handshake option

lib/nghttp2_session.c
The variable data is used possibly unset after a call to 
nghttp2_session_mem_send_internal() which should
set it, however in nghttp2_session_mem_send_internal() it is
possible to return before setting the pointer.
This change initializes the variable to NULL where delcared and
sets the variable in nghttp2_session_mem_send_internal() to
NULL before possibly returning rather than after.
both options are not necessary but are both ideal practice
Note: this tickled the following compilation failure in gcc 4.8.4
nghttp2_session.c: In function 'nghttp2_session_send':
nghttp2_session.c:2942:13: error: 'data' may be used uninitialized in this function [-Werror=maybe-uninitialized]
sentlen = session->callbacks.send_callback(session, data, (size_t)datalen,
^
cc1: all warnings being treated as …
=> in nghttp2_session_send() data is declared uninitialized and used

lib/nghttp2_mem.c, lib/nghttp2_mem.h
=> fix warning: declaration of 'free' shadows a global declaration

lib/nghttp2_hd.c
=> Make get_max_index() return the max index in frame, so we don't need

genlibtokenlookup.py, lib/nghttp2_hd.c
2. Remove inline qualifier of lookup_token() in genlibtokenlookup.py.
=> 1. Modify genlibtokenlookup.py to remove redundant header comparisons.

genlibtokenlookup.py, lib/nghttp2_hd.c
In lstreq(), we will compare the length, but this is not needed in lookup_token(). 
I have looked up the assembly code, and the gcc will optimize the code and remove this comprison during compilation. However, I still think it is the best for us to change it in code.
=> Use memeq() instead of lstreq() in lookup_token().

doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_callbacks.c, lib/nghttp2_callbacks.h, lib/nghttp2_session.c, tests/nghttp2_session_test.c
nghttp2_on_invalid_header_callback is similar to
nghttp2_on_header_callback, but the former is only called when the
invalid header field is received which is silently ignored when the
callback is not set.  With this callback, application inspects the
incoming invalid field, and it also can reset stream from this
callback by returning NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE, or using
nghttp2_submit_rst_stream() directly with the error code of choice.
We also added nghttp2_on_invalid_header_callback2, which uses
reference counted header fields.
=> Add nghttp2_on_invalid_header_callback

lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c, tests/main.c, tests/nghttp2_session_test.c, tests/nghttp2_session_test.h
=> Allow NGHTTP2_ERR_PAUSE from nghttp2_data_source_read_callback

CMakeLists.txt
Without this fix add_subdirectory won't work.
CMAKE_SOURCE_DIR/CMAKE_BINARY_DIR points to the top level
CMakeLists.txt. This isn't necessarily nghttp2/CMakeLists.txt.
=> Make it possible to include nghttp2/CMakeLists.txt in another project

lib/CMakeLists.txt, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_buf.c, lib/nghttp2_debug.c, lib/nghttp2_frame.c, lib/nghttp2_hd.c, lib/nghttp2_session.c, lib/nghttp2_stream.c
This enables applications to take advantage of the DEBUGF statements inside of nghttp2 to fold it into their general logging infrastructure.
=> Add set_nghttp2_debug_callback 

src/shrpx_ssl.cc
As openssl 1.1, boringssl always enable ecdh_auto.
https://boringssl.googlesource.com/boringssl/+/2357%5E!/
=> Fix compilation with BoringSSL

AUTHORS, lib/nghttp2_hd.c
When doing some fuzz testing, I found inputs that caused decode_length to be called in such a way that shift grew to values larger than 32. This is undefined behavior.
=> Prevent undefined behavior in decode_length

script/fetch-ocsp-response
The syntax of openssl ocsp -header option has been changed in OpenSSL
1.1.0.  And it now does not require -header option anymore.  It looks
like that it is workaround for 1.0.x versions.
Fixes #742
=> Fix bug that fetch-ocsp-response does not work with OpenSSL 1.1.0

doc/nghttpx.h2r, src/shrpx_log.cc, src/shrpx_log_config.cc, src/shrpx_log_config.h
To debug multi threaded configuration easier, we added current PID and
thread ID to error log.  Previously, we didn't add date and time if
log level is NOTICE.  In this change, we always write date and time
regardless of log level.
=> nghttpx: New error log format

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_https_upstream.cc
This commit adds frontend-keep-alive-timeout option to nghttpx.  It specifies keep alive timeout for frontend HTTP/1 connection.  Previously, frontend-read-timeout was used for this purpose.
=> nghttpx: Add frontend-keep-alive-timeout option

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_connection.cc, src/shrpx_connection.h, src/shrpx_ssl.cc
This PR adds client-no-http2-cipher-black-list and client-ciphers options.
=> Nghttpx more tls options

src/memchunk.h, src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_http2_upstream.cc, src/shrpx_https_upstream.cc, src/shrpx_spdy_upstream.cc
Previously, we have dedicated read buffer for each frontend
connection.  With this commit, the buffer spaces are only used when
needed, and pooled if they are not used.  This reduces memory usage
for idle client connections.
=> nghttpx: Use Memchunk based read buffer for frontend connection

src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_downstream.h, src/shrpx_http2_upstream.cc, src/shrpx_https_upstream.cc, src/shrpx_log.cc, src/shrpx_log.h, src/shrpx_log_config.cc, src/shrpx_log_config.h, src/shrpx_mruby_module_response.cc, src/shrpx_spdy_upstream.cc
access.log timestamp is now when request header fields are received,
rather than when access log is written.
=> nghttpx: Fix access.log timestamp

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_downstream.cc, src/shrpx_downstream.h, src/shrpx_http2_session.cc, src/shrpx_http_downstream_connection.cc
--accesslog-write-early option is analogous to HAProxy's logasap.  If
used, nghttpx writes access log when response header fields are
received from backend rather than when request transaction finishes.
Fixes #777
=> nghttpx: Add --accesslog-write-early option

src/HtmlParser.cc
This pull requests adds support for link rel="preload" resources in the html [1].
Previously, nghttp used with --get-assets did not download resources indicated to preload.
This behavior is closer to the behavior of a real-world browser such as Firefox.
[1] https://www.w3.org/TR/preload/
=> add support for link rel="preload" for --get-assets

src/asio_server_http2_handler.cc
close_stream just erases the id from the streams_ container which invalidates the iterator.  The who streams_ data structure is about to be deleted anyway so this is unnecessary.
=> close_stream erases from streams_ while it's being iterated over.

src/shrpx-unittest.cc, src/shrpx.cc, src/shrpx_connection_handler.cc, src/shrpx_connection_handler.h, src/shrpx_router.cc, src/shrpx_router.h, src/shrpx_ssl.cc, src/shrpx_ssl.h, src/shrpx_ssl_test.cc, src/shrpx_ssl_test.h
nghttpx supports multiple certificates using --subcert option.
Previously, SNI hostname is used to select certificate.  With this
commit, signature algorithm presented by client is also taken into
consideration.  nghttpx now accepts certificates which share the same
hostname (CN, SAN), but have different signature algorithm (e.g.,
ECDSA+SHA256, RSA+SHA256).
Currently, this feature requires OpenSSL >= 1.0.2.  BoringSSL, and
LibreSSL do not work since they lack required APIs.
Fixes #792
=> nghttpx: Select certificate by client's supported signature algo

src/asio_client_session_impl.cc, src/asio_client_session_tcp_impl.cc, src/asio_client_session_tls_impl.cc
This makes sure objects don't get deleted that are referenced by callbacks inside io_service.
This seems to fix memory issues from my tests with valgrind and -fsanitize=address.  Do you see other errors?  Do you have other tests I should run?
=> Holding more shared_ptrs instead of raw ptrs

configure.ac, contrib/nghttpx.service.in, src/Makefile.am, src/shrpx.cc
Add systemd's Type=notify support by sending information about master process PID around forks. Add some hardening option to service unit.
This improves systemd tracking of main process by explicitly stating which PID is master process. No need to use --pid-file.
daemon() usage is disabled when run under systemd. It make little sense in that context, but more importanly daemon() double forks, leaving us with no time to send a message to systemd.
Please note, even if nghttpx was compiled with systemd support, the resulting binary still can be run under other init systems. sd_notifyf() is no-op if NOTIFY_SOCKET env variable is not set.
I've introduced wrapper for sd_notifyf() function in order to reduce amount of #ifdef's.
There is one harmless message from systemd during forking …
=> nghttpx: add systemd support

src/asio_io_service_pool.cc, src/asio_io_service_pool.h, src/asio_server.cc
Explicit io_service::stop() will prevent running streams from finishing their task. That means if there are  reponses that we have already called end(std::string) on them and they have not finished sending back their data, they will be closed with a NGHTTP2_INTERNAL_ERROR
Instead, we can stop accepting connections and destroy all io_service::work objects to signals end of work.
=> graceful stop of nghttp2::asio_http2::server::http2

doc/nghttpx.h2r, doc/sources/nghttpx-howto.rst, src/shrpx.cc
Previously, after sending SIGUSR2 to the original master process, and
the new master process gets ready, user has to send SIGQUIT to the
original master process to shut it down gracefully.  With this commit,
the new master process sends SIGQUIT to the original master process
when it is ready to serve requests, eliminating for user to send
SIGQUIT manually.
This works nicely with systemd, because now you can replace nghttpx
binary with new one by "systemctl kill -s USR2 nghttpx".
Fixes #804
=> nghttpx: Send SIGQUIT to the original master process

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_ssl.cc, src/shrpx_ssl.h
This commit deprecates --tls-proto-list option, and adds 2 new
options: --tls-min-proto-version and --tls-max-proto-version to
specify minimum and maximum protocol version respectively.  Versions
between the two are enabled.  The deprecated --tls-proto-list has
empty default value, and acts like disabling specific protocol version
in the range for now.
Fixes #809
=> nghttpx: Specify TLS protocol by version range

src/HttpServer.cc, src/h2load.cc, src/nghttp.cc, src/shrpx.cc, src/shrpx_ssl.cc, src/ssl.cc, src/ssl.h
Fixes #764 
This enables TLSv1.3 for all applications under src (nghttp, nghttpd, nghttpx, and h2load) if OpenSSL supports it.  Currently OpenSSL master and BoringSSL enable TLSv1.3.  OpenSSL's TLSv1.3 support is still WIP.  And TLSv1.3 itself is not finalized yet.
=> Add TLSv1.3 support

gennghttpxfun.py, integration-tests/nghttpx_http1_test.go, integration-tests/nghttpx_http2_test.go, integration-tests/server_tester.go, src/shrpx-unittest.cc, src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_error.h, src/shrpx_http2_upstream.cc, src/shrpx_http2_upstream.h, src/shrpx_http_downstream_connection.cc, src/shrpx_https_upstream.cc, src/shrpx_https_upstream.h, src/shrpx_spdy_upstream.cc, src/shrpx_spdy_upstream.h, src/shrpx_upstream.h, src/shrpx_worker.cc, src/shrpx_worker.h, src/util.cc, src/util.h, src/util_test.cc, src/util_test.h
This commit removes frontend-tls parameter, and adds
redirect-if-not-tls parameter parameter to --backend option.  nghttpx
now responds to the request with 308 status code to redirect the
request to https URI if frontend connection is not TLS encrypted, and
redirect-if-no-tls parameter is used in --backend option.  The port
number in Location header field is 443 by default (thus omitted), but
it can be configurable using --redirect-https-port option.
=> nghttpx: Redirect to HTTPS URI with redirect-if-no-tls parameter in backend option

doc/nghttpx.h2r, integration-tests/nghttpx_http1_test.go, integration-tests/nghttpx_http2_test.go, integration-tests/server_tester.go, src/shrpx.cc, src/shrpx_api_downstream_connection.cc, src/shrpx_api_downstream_connection.h, src/shrpx_config.h
This commit adds configuration revision, which is considered opaque
string, and changes after reloading configuration with SIGHUP.  This
revision is returned as a response to configrevision API endpoint.
This allows external application to know whether nghttpx has finished
reloading new configuration or not.  Note that this revision does not
change on backendconfig API calls.
=> Nghttpx configrevision api

CMakeLists.txt, cmakeconfig.h.in, configure.ac, examples/client.c, examples/deflate.c, examples/libevent-client.c, examples/libevent-server.c, lib/Makefile.msvc, lib/nghttp2_debug.c, lib/nghttp2_frame.c, lib/nghttp2_frame.h, lib/nghttp2_hd.c, lib/nghttp2_http.c, lib/nghttp2_mem.c, lib/nghttp2_session.c, lib/nghttp2_stream.c, lib/nghttp2_submit.c, tests/failmalloc.c, tests/failmalloc_test.c, tests/main.c, tests/malloc_wrapper.c, tests/nghttp2_map_test.c, tests/nghttp2_pq_test.c, tests/nghttp2_session_test.c, tests/nghttp2_test_helper.c
Instead use (void)VAR for better compiler compatibility.
Fixes #840
=> Eliminate _U_ macro

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h
With --single-process option, nghttpx will run in a single process
mode where master and worker are unified into one process.  nghttpx
still spawns additional process for neverbleed.  In the single process
mode, signal handling is disabled.
Fixes #869
=> nghttpx: Add --single-process option

gennghttpxfun.py, integration-tests/nghttpx_http2_test.go, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_http2_downstream_connection.cc, src/shrpx_http_downstream_connection.cc
This PR fixes #872 differently from the way that #873 does.
#873 has been reverted.
This PR adds new options without breaking the existing behaviour.
=> Nghttpx xfp take2

src/asio_client_session.cc, src/asio_client_session_impl.cc, src/asio_client_session_impl.h, src/includes/nghttp2/asio_http2_client.h
i noticed that the C++ API doesn't pass along priority (just passes `nullptr` currently), so i thought a clean way to do this (without exposing the underlying nghttp2 types) would be to just create a simple wrapper that could be passed along, whose sentinel value would result in the same `nullptr` argument to `nghttp2_submit_request` (i.e. no specified priority), but when properly constructed, would pass an `nghttp2_priority_spec*`.
for convenience, it also seemed reasonable that `priority_spec` ctor should be easily usable by providing the most common arguments first, i.e., trivially used to represent weight (e.g. `priority_spec(4.0)`).
i need this on my end, so happy to make any adjustments you'd like!
=> Support specifying stream priority via session::submit()

src/shrpx_worker.cc, src/shrpx_worker_test.cc
Previously, if path is empty or path does not start with "/", nghttpx
did not try to match with wildcard pattern.  This commit fixes it.
This will fix the issue reported in #733
=> nghttpx: Fix path matching bug

src/http2.cc, src/http2.h, src/http2_test.cc, src/shrpx_http2_downstream_connection.cc, src/shrpx_http2_upstream.cc, src/shrpx_http_downstream_connection.cc, src/shrpx_https_upstream.cc
Previously, for Via, X-Forwarded-For, and X-Forwarded-Proto header
field, nghttpx only forwarded the last header field of each.  With
this commit, nghttpx forwards all of them if it is configured to do
so.
=> nghttpx: Forward multiple via, xff, and xfp header fields

src/nghttp.cc, src/nghttp.h
=> nghttp: Add -y, --no-verify-peer option to suppress peer verify warn

src/shrpx-unittest.cc, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_router.cc, src/shrpx_router.h, src/shrpx_router_test.cc, src/shrpx_router_test.h
This commit adds wildcard path matching.  If path pattern given in
backend option ends with "\*", it is considered as wildcard path.  "\*"
must match at least one character.  All paths which include wildcard
path without last "\*" as prefix, and are strictly longer than wildcard
path without last "\*" are matched.
Fixes #914
=> nghttpx: Wildcard path matching

doc/programmers-guide.rst, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c, tests/nghttp2_session_test.c
Previously, the incoming invalid regular header field was ignored by
default.  With this commit, they are now treated as stream error, and
the stream is reset by default.  The error code used is now
PROTOCOL_ERROR, instead of INTERNAL_ERROR.
Fixes #900
=> Treat incoming invalid regular header field as stream error

lib/nghttp2_session.c
Hi,
This is a very small fix for building with -DNDEBUG set (as described in 0c49e5d56e3). If assert is compiled out, these functions otherwise fail to compile as they don't return a value.
Can replace the `assert(0)`s entirely if that's desirable, but I noticed abort() isn't used anywhere else in the library code so I figure this keeps consistency - if NDEBUG is not set then the abort() call should be compiled out as unreachable code.
Thanks for all your work maintaining this library. :)
=> nghttp2_session: Allow for compiling library with -DNDEBUG set

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_connection_handler.cc, src/shrpx_connection_handler.h, src/shrpx_worker_process.cc
With --ocsp-startup option, nghttpx starts accepting connections after
initial attempts to get OCSP responses finish.  It does not matter
some of the attempts fail.  This feature is useful if OCSP responses
must be available before accepting connections.
=> nghttpx: Run OCSP at startup

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_connection_handler.cc, src/shrpx_tls.cc, src/shrpx_tls.h
At least we should make sure that the OCSP response is targeted to the
expected certificate.  This is important because we pass the file path
to the external script, and if the file is replaced because of
renewal, and nghttpx has not reloaded its configuration, the
certificate nghttpx has loaded and the one included in the file
differ.  Verifying the OCSP response detects this, and avoids to send
wrong OCSP response.
=> nghttpx: Verify OCSP response

doc/Makefile.am
The altered line previously failed if the rst sources hadn't been copied over.
=> fix cleaning in out-of-tree builds

src/shrpx.cc
Previously, the default minimum TLS version was TLSv1.1, but the
default cipher list didn't include any compatible ciphers with it.
This made handshake fail if TLSv1.1 was negotiated because there was
no shared ciphers.  To make the default settings consistent, the
default minimum TLS version is now TLSv1.2.
Addresses #937
=> nghttpx: Set default minimum TLS version to TLSv1.2

src/nghttp.cc
=> nghttp: Fix bug that upgrade fails if reason-phrase is missing

doc/CMakeLists.txt, doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_rcbuf.c
Add a `nghttp2_rcbuf_is_static()` method to tell whether a rcbuf
is statically allocated.
This can be useful for language bindings that wish to avoid
creating duplicate strings for these buffers; concretely, I am
planning to use this in the Node HTTP/2 module that is being
introduced.
=> lib: add nghttp2_rcbuf_is_static()

examples/CMakeLists.txt, lib/CMakeLists.txt, src/CMakeLists.txt
Refactoring include directories for build as CMake subdirectory (add_subdirectory(nghttp2))
Example: https://github.com/dvetutnev/tst_nghttp2
=> Refactoring include directories

src/h2load.cc, src/h2load.h
This option will enable timing-based load-testing in h2load. Users can specify warm-up and main duration of the load-test. There will be no finite number of requests given.` h2load` will try to generate as many requests as possible, both during warm-up and the main duration period. However, statistics such as the total `req/s` will be calculated only for the main duration period.
For this test to run, we can invoke h2load by the following command, for example:
`h2load -c 10 -t 2 -D 5 --warm-up-time 5 -n 0 https://localhost:4500`
The above says that there will be 10 clients for 2 threads with 5 seconds of warm-up time and 5 seconds of main duration of load-test. `-n` needs to be set to zero for timing-based test.
=> Enabling timing-based load-testing in h2load

src/shrpx_tls.cc
BoringSSL has no `openssl/ocsp.h` nor most OCSP related APIs used in
`shrpx_tls.cc`. This commit add ifdefs to disable related code to allow
building nghttp2 with BoringSSL (again).
It's possible to use `!defined(OPENSSL_IS_BORINGSSL)`, but since BoringSSL
defines `OPENSSL_NO_OCSP` which is more specific, I chose to go with the
latter one.
=> Fix OCSP related error when building with BoringSSL

CMakeLists.txt, README.rst, configure.ac
It's currently set at 2.7.7 but reducing this down to 2.6.26 allows nghttp2 to be built on RHEL5
=> Reduce libxml2 version requirement to 2.6.26

CMakeLists.txt
Your CMake script replaces /DNDEBUG compiler option with empty script.
But if CMAKE_C_FLAGS_{build} contains /DNDEBUG in the middle of other compiler switches then replacing it with empty string concatenates neighboring switches into one. And that make Visual Studio unhappy because it can not recognize that we have 2 switches and not 1.
In my case `/Oi /Gy /DNDEBUG /Z7` became `/Oi /Gy/Z7` and VS for some reason thinks that /Gy/Z7 is a single /GZ switch.
This patch eliminate the issue. In general extra space should not matter and in this particular case it will solve the problem with switches.
=> Fixed accidental compiler flags concatenation for MSVC.

doc/nghttpx.h2r, src/shrpx_mruby_module_env.cc, src/shrpx_tls.cc, src/shrpx_tls.h
This adds tls_client_fingerprint, and tls_client_subject_name to mruby Env object.
See #1031
=> nghttpx: Add client fingerprint and subject name to mruby env

doc/nghttpx.h2r, src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_mruby_module_env.cc
The added attributes are:
* tls_cipher
* tls_protocol
* tls_session_id
* tls_session_reused
* alpn
See #1031
=> nghttpx: Add more TLS related attributes to mruby Env object

lib/nghttp2_session.c
The error code NGHTTP2_REFUSED_STREAM is passed to
nghttp2_on_stream_close callback when a stream is closed because its
stream ID is strictly larger than incoming or outgoing GOAWAY.
=> Use NGHTTP2_REFUSED_STREAM for streams which are closed by GOAWAY

src/shrpx_http2_session.cc
=> nghttpx: Fix crash with --backend-http-proxy-uri option

src/shrpx_downstream.h, src/shrpx_http2_upstream.cc
Remember which resource is pushed in order to conform to the semantics
described in RFC 8297.
=> nghttpx: Remember which resource is pushed

src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_http2_downstream_connection.cc, src/shrpx_worker.cc, src/shrpx_worker.h
If "upgrade-scheme" parameter is present in backend option along with
"tls" paramter, HTTP/2 :scheme pseudo header field is changed to
"https" from "http" when forwarding a request to this particular
backend.  This is a workaround for a server which requests "https"
scheme on HTTP/2 connection encrypted by TLS.
Fixes #1099
=> nghttpx: Add upgrade-scheme parameter to backend option

src/shrpx_mruby_module_request.cc
Fixes #1119.
Fixes a simple logic bug where the first header will be overwritten when the replacement header is not equal to the first header in the header hashmap. In this scenario, after `p == i == 0`, then `p == (i - 1)`, which iteratively overwrites the previous value, starting with index 0 (the first header), then resizes the array to `size() - 1`.
This patch fixes the bug so that `p != i` iff at least one header key has matched the replacement header key.
=> Fix #1119: Overwrite of first header on mruby call to env.req.set_header(..)

CMakeOptions.txt, lib/CMakeLists.txt
When using the `ENABLE_LIB_ONLY` option, only the shared library was built. This new option allows to build the static library as well.
=> cmake: add ENABLE_STATIC_LIB option to build static lib

examples/client.c, examples/libevent-client.c, examples/libevent-server.c, src/HttpServer.cc, src/asio_common.cc, src/h2load.cc, src/nghttp.cc, src/shrpx_client_handler.cc, src/shrpx_connection.cc, src/shrpx_http2_session.cc, src/shrpx_live_check.cc, src/shrpx_tls.cc
NPN has been superseeded by ALPN. OpenSSL provides a configure
option to disable npn (no-npn) which results in an OpenSSL
installation that defines OPENSSL_NO_NEXTPROTONEG in opensslconf.h
The #ifdef's look safe here (as the next_proto is initialized as
nullptr). Alteratively, macros could be defined for the used npn
methods that return a 0 for next_proto.
Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>
=> [PATCH] Allow building without NPN

lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c, lib/nghttp2_session.h, tests/nghttp2_session_test.c
The maximum number of outgoing concurrent streams is initially
limited to 100 to avoid issues when the local endpoint submits
lots of requests before receiving initial SETTINGS frame from
the remote endpoint, since sending them at once to the remote
endpoint could lead to rejection of some of the requests.
This initial limit is overwritten with the value advertised in
SETTINGS_MAX_CONCURRENT_STREAMS setting by the remote endpoint,
but previously, it wasn't lifted if the remote endpoint didn't
advertise that setting (implying no limits), in which case the
limit of 100 was retained, even though it was never advertised
by the remote endpoint.
=> Fix handling of SETTINGS_MAX_CONCURRENT_STREAMS.

lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c, tests/main.c, tests/nghttp2_session_test.c, tests/nghttp2_session_test.h
nghttp2_session_set_stream_user_data now works for a stream which is
not created yet, but the request which creates the stream is queued.
=> Tweak nghttp2_session_set_stream_user_data

src/asio_client_session_tcp_impl.cc
Hi Tatsuhiro,
I revisited the asio client local endpoint code and I think it makes more sense to do it like this.
The previous code might be problematic if local_endpoint is ipv6.
Best regards,
Alexandros
=> fix code for reuse addr on asio client

gennghttpxfun.py, src/http2.cc, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_connection.cc, src/shrpx_connection.h, src/shrpx_http2_downstream_connection.cc, src/shrpx_http_downstream_connection.cc, src/shrpx_rate_limit.cc, src/shrpx_tls.cc
With this path, and if compiled with latest OpenSSL master branch, nghttpx gets TLSv1.3 0-RTT early data support.
=> nghttpx: Enable TLSv1.3 0-RTT early data support

lib/includes/nghttp2/nghttp2.h
Clang compilation targets may support `__declspec` attributes. Because of that it has a `__has_declspec_attribute` [check](https://clang.llvm.org/docs/LanguageExtensions.html#has-declspec-attribute).
Currently nghttp2 just assumes that `__declspec` is Windows only. This adds a compatibility macro and checks whether `dllimport` and `dllexport` are available.
=> Use __has_declspec_attribute for shared builds

cmake/FindLibevent.cmake
On my x86_64 Gentoo Linux, the CMake build won't find libevent because Gentoo wraps include files via multilib-aware wrappers. This means that the "real" include file lives in `/usr/include/x86_64-pc-linux-gnu/event2/event-config.h`, and that there's a proxy file at `/usr/include/event2/event-config.h` which check the compile target's architecture and includes the real file from a correct directory.
In other words, nghttp2's CMake `FindLibevent.cmake` reads a wrong file and ends up not detecting the libevent's version.
This patch fixes it by simply using the version reported by `pkg-config` as the libevent's version if the original method fails. I will be happy to change this patch to always check version from pkg-config if you're OK with that.
=> cmake: Fix libevent version detection

src/shrpx_router.cc, src/shrpx_router_test.cc
nghttpx allows a pattern with trailing slash to match a request path
without it.  Previously, under certain pattern registration, this does
not work.
=> nghttpx: Fix broken trailing slash handling

.travis.yml
It is now possible to use Xenial (Ubuntu 16.04) on Travis
Also no longer need to get external clang (on Travis Xenial, it is clang-7)
=> Travis: Update to Xenial

CMakeOptions.txt, lib/CMakeLists.txt
Adds a CMake option `ENABLE_SHARED_LIB` (default ON) that determines if the shared library is built.
Signed-off-by: Brendan Heinonen <brendan@heinonen.co>
=> Add a CMake option to disable shared library

src/shrpx_tls.cc
From https://www.ietf.org/rfc/rfc5280.txt
> As noted in Section 4.1.2.2, serial numbers can be expected to
> contain long integers.  Certificate users MUST be able to handle
> serialNumber values up to 20 octets in length.  Conforming CAs MUST
> NOT use serialNumber values longer than 20 octets.
Without this, nghttpx will fatal.
jbraeg$ openssl x509 -in ~/test_certs/client.crt -serial -noout
serial=E0CFDFC7CEA10DF8AAF715C37FAEB410
jbraeg$ curl -k --key ~/test_certs/client.key --cert ~/test_certs/client.crt https://192.168.98.100:3000/; echo
curl: (56) Unexpected EOF
...
Assertion failed: n == b.size() (shrpx_tls.cc: get_x509_serial: 2051)
2019-01-03T20:25:21.289Z 1 1 f84316ae NOTICE (shrpx_log.cc:895) Worker process: [9] exited abnormally with status 0x06; exit status 0; signal Aborted(6) …
=> Fix getting long serial numbers for openssl < 1.1

src/asio_server_connection.h
In boost 1.70, deprecated get_io_context() has finally been removed.
Introduce GET_IO_SERVICE macro that based on boost version uses
old get_io_service() interface (boost < 1.70), or get_executor().context()
for boost 1.70+.
Commit based on idea seen in monero-project/monero@17769db9462e5201befcb05f86ccbaeabf35caf8
=> asio: support boost-1.70

lib/nghttp2_http.c, src/shrpx_downstream.cc, src/shrpx_downstream.h, src/shrpx_http_downstream_connection.cc, tests/nghttp2_session_test.c
Ignore Content-Length and Transfer-Encoding in 200 response to CONNECT request as per RFC 7230.
I found that a well known server sends content-length: 0 in 101 response to HTTP Upgrade.  nghttpx now ignores content-length in this case.
=> Ignore Content-Length and Transfer-Encoding in 200 response to CONNECT request

.travis.yml, configure.ac, src/nghttpd.cc, src/shrpx.cc, src/util.cc, src/util.h
Enable OSX build on travis to make sure that nghttp2 can be built on it.
I observed that at least xcode 10.2 can compile nghttp2 successfully.
=> Travis osx

src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_log.cc, src/shrpx_log.h
Previously, if log-level is not mentioned in configuration file and
reload happens, the log level was not set to the default value NOTICE.
Instead, the log level stayed the same.  This commit fixes this bug.
=> nghttpx: Fix unchanged log level on configuration reload

integration-tests/nghttpx_http1_test.go, integration-tests/server_tester.go, src/shrpx_downstream.cc, src/shrpx_downstream.h, src/shrpx_http_downstream_connection.cc, src/shrpx_https_upstream.cc
Fix request stall if backend connection is reused and buffer is full.
=> nghttpx: Fix request stall

src/shrpx_downstream.cc, src/shrpx_http2_upstream.cc, src/shrpx_https_upstream.cc, src/shrpx_worker.cc, src/shrpx_worker.h
Previously, mruby context is wrongly shared by multiple patterns if
the underlying SharedDownstreamAddr is shared by multiple
DownstreamAddrGroups.  This commit fixes it.
=> nghttpx: Fix bug that mruby is incorrectly shared between backends

lib/CMakeLists.txt
Renames the output of the ENABLE_STATIC_LIB library/archive output
to nghttp2_static.lib/.a to avoid filenames colliding with the output
name for ENABLE_SHARED_LIB library/archive, when both are enabled.
This change requires a release notes notice.
Signed-off-by: William A Rowe Jr <wrowe@pivotal.io>
Signed-off-by: Yechiel Kalmenson <ykalmenson@pivotal.io>
=> Avoid filename collision of static and dynamic lib

src/asio_client_session.cc, src/includes/nghttp2/asio_http2_client.h
gcc generates warning:
* type qualifiers ignored on function return type [-Wignored-qualifiers]
=> priority_spec::valid(): remove const qualifier from return value

lib/nghttp2_session.c, tests/nghttp2_session_test.c
This commit fixes the bug that stream is closed with wrong error code
(0).  This happens when STREAM or DATA frame with END_STREAM flag set
is received and it violates HTTP messaging rule (i.e., content-length
does not match).  In this case, nghttp2_on_stream_close_callback
should be called with nonzero error code, but previously it is called
with 0 (NO_ERROR).
Fixes #1408
=> Fix the bug that stream is closed with wrong error code

lib/CMakeLists.txt
It can be set via the `STATIC_LIB_SUFFIX` variable.
This fixes every existing dependent project that relied on the name
having no suffix and thus capable of using either a static or shared
flavour depending on which one is present on this or how the linker
is configured.
Ref: https://github.com/nghttp2/nghttp2/pull/1394
=> lib/CMakeLists.txt: Make hard-coded static lib suffix optional

tests/main.c, tests/nghttp2_session_test.c
Add the currently-unused `test_nghttp2_session_create_idle_stream()`
function to the test suite definition.
Modify the test in two places to make it pass:
* Use stream ID=10 as the priority stream ID to test automatic creation
of streams for priority specs. The code below checks against stream
ID=10 so I assume this was a typo in the test.
* Set the `last_sent_stream_id` instead of the `next_stream_id` to test
that idle streams cannot be created with smaller numbers than the
most-recently-seen stream ID. Looking at the validation path in
`session_detect_idle_stream()`, I think this was another test typo.
=> Enable session_create_idle_stream test, fix errors

lib/nghttp2_session.c, lib/nghttp2_session.h, lib/nghttp2_submit.c, tests/nghttp2_session_test.c
Previously, if automatic window update is enabled (which is default),
after window size is set to 0 by
nghttp2_session_set_local_window_size, once the receiving window is
exhausted, even after window size is increased by
nghttp2_session_set_local_window_size, no more data cannot be
received.  This is because nghttp2_session_set_local_window_size does
not submit WINDOW_UPDATE.  It is only triggered when new data arrives
but since window is filled up, no more data cannot be received, thus
dead lock happens.
This commit fixes this issue.  nghttp2_session_set_local_window_size
submits WINDOW_UPDATE if necessary.
https://github.com/curl/curl/issues/4939
=> Fix receiving stream data stall

src/shrpx_tls.cc
- Under OpenSSL >= 1.1, `get_x509_serial` would return an empty `StringRef` if the client certificate serial number was greater than 8 bytes long
- Under OpenSSL < 1.1, `get_x509_serial` would return a `StringRef` with the last `(20 - n)` bytes set to nondeterministic garbage and the first `n` bytes set to the correct serial number, where `n` is the length of the serial number.
- This commit unifies the code paths in `get_x509_serial` for all OpenSSL versions and fixes the function to return a `StringRef` of equal length as the serial number.
=> Fix get_x509_serial for long serial numbers

lib/includes/nghttp2/nghttp2.h
The previous wording implied that if send_callback doesn't return
NGHTTP2_ERR_WOULDBLOCK, this function would always send all
submitted requests / data. This is not the case, since flow control can
cause some data to remain queued until WINDOW_UPDATE is received.
=> doc: clarify flow control behaviour for nghttp2_session_send()

lib/includes/nghttp2/nghttp2.h
Further clarify the function also takes into account maximum concurrent
streams.
Closes #691
Closes #817
=> doc: nghttp2_session_send is also affected by max concurrent streams

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_log.cc, src/shrpx_log.h
This commit the following variables to construct request line without
including query component:
* $method
* $path
* $path_without_query
* $protocol_version
=> nghttpx: Add accesslog variables to record request path without query

src/includes/nghttp2/asio_http2_client.h, src/includes/nghttp2/asio_http2_server.h
Really just a `s/pusedo/pseudo/g` and `s/exluced/excluded/g`.
=> docs: asio: fix some typos

src/h2load.cc, src/h2load.h, src/h2load_quic.cc
This PR adds an option for h2load to generate per-connection qlog output, which will help troubleshooting interoperability/performance issues.
=> h2load: Add qlog output support

src/HttpServer.h
Summary:
The [data_flags](https://github.com/lhuang04/nghttp2/blob/master/src/HttpServer.cc#L1078) is defined as `uint32_t*` in definition, but delared as [int*](https://github.com/lhuang04/nghttp2/blob/master/src/HttpServer.h#L245) in the prototype.
```
stderr: error: no previous prototype for function 'file_read_callback' [-Werror,-Wmissing-prototypes]
ssize_t file_read_callback(nghttp2_session *session, int32_t stream_id,
^
```
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:
=> Fix prototype mismatch for function 'file_read_callback'

lib/includes/nghttp2/nghttp2.h
I think nghttp2_session_mem_recv is able to receive only inlen bytes of data instead of all.
I am trying to make the document clearer.
Also expect to update this page too: [nghttp2_session_mem_recv](https://nghttp2.org/documentation/nghttp2_session_mem_recv.html#c.nghttp2_session_mem_recv)
reference issue:  #1600
=> update doc for nghttp2_session_mem_recv

docker/Dockerfile
Thank you so much for the wonderful project!
I found the Dockerfile emits a warning below and can not speak HTTP/3.
```
2021-12-12T14:02:21.285Z 1 1 4ca9edca WARN (shrpx.cc:3658) --fetch-ocsp-response-file: /usr/local/share/nghttp2/fetch-ocsp-response not found.  OCSP stapling has been disabled.
...
```
So, the PR copies `/usr/local/share/nghttp2/`.
I did docker-build the fixed Dockerfile as `nghttp2` image and docker-run as follows. Suppose an HTTP server is running on localhost:80.
```bash
docker run --rm -it -v /etc/letsencrypt/live/ex.nwtgck.org/privkey.pem:/shared/server.key -v /etc/letsencrypt/live/ex.nwtgck.org/fullchain.pem:/shared/server.crt --net=host --privileged nghttp2 nghttpx --add-response-header='alt-svc: h3=":8443"; ma=3600, h3-29=":8443"; ma=3600' /shared/server.key …
```
=> Make Docker speak HTTP/3

CMakeOptions.txt
SPDY feature was removed in #1091 and release v1.29.0
=> Remove SPDY option for CMake

lib/nghttp2_hd.c, tests/nghttp2_hd_test.c, tests/nghttp2_session_test.c
When applying new header table size acknowledged with SETTINGS ACK by
an encoder, change the header table size on a decoder only when it
strictly lowers the current maximum table size set by Dynamic Table
Size Update from the encoder or the default size 4096 if no Dynamic
Table Size Update is received.
Previously, the header table size on a decoder is always changed.  If
a maximum size in SETTINGS are increased (e.g., 4096 -> 8192), and
then decreased to the previous value, the decoder incorrectly requires
Dynamic Table Size Update from an encoder.
=> Fix decoder table size update

doc/nghttpx.1, doc/nghttpx.1.rst, src/shrpx.cc
Thank you so much for the wonderful project.
I just corrected --altsvc example: `"...'` → `"..."`.
=> fix quotes in --altsvc example

lib/nghttp2_session.c, tests/nghttp2_session_test.c
Fix the bug that causes a stream to stall when a receiver, which
enables nghttp2_option_set_no_auto_window_update() option on, sends
SETTINGS_INITIAL_WINDOW_SIZE with the value that is less than or equal
to the amount of data received.  Previously, in this particular case,
when SETTINGS is acknowledged by the sender, the receiver does not try
to send WINDOW_UPDATE frame.  The sender is unable to send more data
because its stream-level window size is smaller than or equal to the
amount of data it has sent.
Fixes #1679
=> Fix stream stall when initial window size is decreased

src/shrpx_worker.cc
Session affinity has been broken since
fdcdb21c38ef7acf23853d47d1dc5bda69d5398f.  This commit reverts the
relevant part of the commit to fix the session affinity.
=> nghttpx: Fix broken session affinity

lib/nghttp2_http.c, tests/nghttp2_session_test.c
Do not verify host field specific characters for response field
section because host field in response field section is undefined.
Fixes #1726
=> Do not verify host field specific characters for response field

doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_option.c, lib/nghttp2_option.h, lib/nghttp2_session.c, lib/nghttp2_session.h, tests/main.c, tests/nghttp2_session_test.c, tests/nghttp2_session_test.h
Add nghttp2_option_set_server_fallback_rfc7540_priorities.  If it is
set to nonzero, and server submits SETTINGS_NO_RFC7540_PRIORITIES = 1,
but it does not receive SETTINGS_NO_RFC7540_PRIORITIES from client,
server falls back to RFC 7540 priorities.  Only minimal set of
features are enabled in this fallback case.
=> Add a server option to fallback to RFC 7540 priorities

src/shrpx.cc, src/shrpx_http2_session.cc, src/shrpx_http2_upstream.cc
Disable RFC 7540 priorities in nghttpx.  It enables RFC 9218
extensible prioritization scheme.  It also enables a mechanism for
server to fallback to RFC 7540 in order to handle the existing clients
which do not implement SETTINGS_NO_RFC7540_PRIORITIES.
=> nghttpx: Disable RFC 7540 priorities

doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c, lib/nghttp2_stream.h, tests/main.c, tests/nghttp2_session_test.c, tests/nghttp2_session_test.h
Allow server to override RFC 9218 stream priority with
nghttp2_session_change_extpri_stream_priority.
=> Allow server to override RFC 9218 stream priority

lib/nghttp2_http.c
No need to check pseudo header lws because it is guaranteed not to
have leading white spaces.
=> No need to check pseudo header lws

integration-tests/nghttpx_http2_test.go, integration-tests/server_tester.go, src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_connection.cc, src/shrpx_connection.h
Fix PROXY-protocol that is enabled for TLS connection.
Fixes #1746
=> nghttpx: Fix broken PROXY-protocol

src/shrpx_worker.cc, src/util.h
This is the 2nd attempt to randomize backend address round robin
order.
The initial attempt of doing this was
fdcdb21c38ef7acf23853d47d1dc5bda69d5398f, which has been reverted via
470f06e5f6deab5284ffe93f15cc4ce8b16ee2ec because it broke the session
affinity.
This time, we shuffles seq fields and avoid reordering addrs vector.
=> nghttpx: Randomize backend address backend robin order per thread (2nd Ed.)

src/CMakeLists.txt, src/Makefile.am, src/deflatehd.cc, src/h2load.cc, src/nghttp.cc, src/nghttpd.cc, src/shrpx_config.cc
Replace the use of strtoul and strtol with parse_uint to fix the
handling of negative integer.
Fixes #1774
=> Replace the use of strtoul and strtol with parse_uint

fuzz/fuzz_target_fdp.cc
Similar in nature to fuzz_target.cc but adds the difference of a random
iv constructed by way of fuzzer data. This fuzzer achieves higher code
coverage than fuzz_target.cc but I think we should create a new rather
than extend the existing to keep corpus of the existing.
=> fuzz: add extended fuzzer using FuzzedDataProvider

fuzz/fuzz_frames.cc
Adds a fuzzer heavily inspired by https://github.com/nghttp2/nghttp2/blob/master/tests/nghttp2_frame_test.c The key goal is to increase code coverage of `nghttp2_frame.c`. Extensions are possible but would start with this.
This PR sets up relevant OSS-Fuzz changes: https://github.com/google/oss-fuzz/pull/8149
Am not entirely sure how much documentation is preferred, could you advise? I assume the existing fuzzer in practice only runs by way of OSS-Fuzz.
One thing this fuzzer does differently in comparison to the existing fuzzer is use `FuzzedDataProvider` interface to generate random strings. See here for documentation on this class: https://github.com/google/fuzzing/blob/master/docs/split-inputs.md
=> fuzz: add frames fuzzer

Dockerfile.android
1.40.0 is the last version that can make a successful build with this Dockerfile, build failed start from 1.41.0
Updated some dependency versions
Fixed a typo
=> Update dependency versions for Dockerfile.android

Dockerfile.android, configure.ac
The latest nghttp2 release version cannot be built with the latest NDK.  The nghttp2 version in Dockerfile points to master for now.
=> Bump NDK and others to the latest

src/shrpx_config.cc
Fix affinity-cookie-stickiness backend parameter handling. Previously, if 3 backend options are used for the same pattern, and the first one does not have affinity-cookie-stickiness, and the rest of them have affinity-cookie-stickiness=strict, nghttpx wrongly determines that they have inconsistent configurations.
=> nghttpx: Fix affinity-cookie-stickiness parameter handling

third-party/CMakeLists.txt, third-party/Makefile.am, third-party/build_config.rb
Support mruby cross build, but now we are unable to specify host C/C++ compiler on cross build.
Do not pass compiler and linker flags because mruby does its own.
Cross build only works with autotools.  It does not work with cmake.
=> mruby: Support cross build for autotools

src/shrpx.cc
=> nghttpx: Header field name must be lowercase

CMakeLists.txt, Makefile.am, cmake/PickyWarningsC.cmake, cmake/PickyWarningsCXX.cmake
This patch makes CMake configuration faster by dropping feature checks
for each individual "picky" C/C++ compiler warning options and instead
enable them based on compiler version. It also allows to add options using
the old, feature-check method.
I've implemented this for libssh2 [1], curl [2] and ngtcp2 [3] earlier.
This patch is based on those, by adapting it to the warning options used
by nghttp2.
It brings CMake configuration time down from 22 to 15 seconds on my local
machine.
Also add missing `WARNCXXFLAGS` to the build config summary.
[1] libssh2
https://github.com/libssh2/libssh2/commit/ec0feae7920d695ce234a5aba13014bf29824c09
https://github.com/libssh2/libssh2/pull/952
[2] curl
https://github.com/curl/curl/commit/9c543de0ecf14880c3324d3d24591fb695dd1917 …
=> cmake: speed up warning option detection

CMakeLists.txt, cmakeconfig.h.in, configure.ac, lib/nghttp2_time.c
This is the recommended way of including Windows headers:
https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount64
> Header: sysinfoapi.h (include Windows.h)
=> Use `#include <windows.h>` instead of `#include <sysinfoapi.h>`

CMakeLists.txt, configure.ac
Previously, SSL_is_quic is used to detect quictls.  But OpenSSL 3.2 has added it as a part of its own QUIC implementation which breaks our script.  Use SSL_provide_quic_data to correctly identify quictls and avoid OpenSSL 3.2.
=> Avoid detecting OpenSSL 3.2 as quictls

doc/sources/tutorial-client.rst, doc/sources/tutorial-server.rst, examples/client.c, examples/libevent-client.c, examples/libevent-server.c, src/HttpServer.cc, src/h2load.cc, src/nghttp.cc, src/shrpx_client_handler.cc, src/shrpx_connection.cc, src/shrpx_http2_session.cc, src/shrpx_live_check.cc, src/shrpx_tls.cc
All OpenSSLs that we support have ALPN and SSL_get_server_tmp_key.
=> Drop old OpenSSL support part 2

src/shrpx_tls.cc
OpenSSL needs SSL_CTX_set_recv_max_early_data as well as SSL_CTX_set_max_early_data to properly set acceptable max early data size.
=> nghttpx: OpenSSL needs SSL_CTX_set_recv_max_early_data

CMakeLists.txt
We shouldn't need to call `find_package()` on dependencies that aren't required. As per the README:
> If you need libnghttp2 (C library) only, then the above packages are all you need. Use --enable-lib-only to ensure that only libnghttp2 is built. This avoids potential build error related to building bundled applications.
> To build and run the application programs (nghttp, nghttpd, nghttpx and h2load) in the src directory, the following packages are required:
> OpenSSL >= 1.1.1; or LibreSSL >= 3.8.1; or aws-lc >= 1.19.0; or BoringSSL
> libev >= 4.11
> zlib >= 1.2.3
> libc-ares >= 1.7.5
This change fixes that.
=> Not finding packages when `ENABLE_LIB_ONLY` is set

CMakeLists.txt, cmakeconfig.h.in, configure.ac, lib/nghttp2_time.c, src/timegm.c, src/timegm.h, src/util.cc
Speeds up the build minimally, doesn't check for stuff that's always there.
=> Have less stuff in config.h

src/shrpx_http3_upstream.cc, src/shrpx_http3_upstream.h
This reverts commit e103726f4d39a6cbcd29381f10fb837a1361b3a5.
See #2035
=> Revert "nghttpx: Shutdown h3 stream write if reset by a remote endpoint"

lib/includes/nghttp2/nghttp2.h
This commit just adds a warning to the related API documents.  The actual functionality works just like before.
=> Deprecate RFC 7540 priorities (aka stream dependencies)

src/shrpx_http3_upstream.cc, src/shrpx_quic.h
Remove SHRPX_QUIC_MAX_UDP_PAYLOAD_SIZE and just rely on the ngtcp2 default.
=> nghttpx: Remove SHRPX_QUIC_MAX_UDP_PAYLOAD_SIZE

src/shrpx_config.cc, src/shrpx_tls_test.cc
Fixes for older macOS (and possibly some other platforms where `AI_NUMERICSERV` is not available).
=> Fix build when `AI_NUMERICSERV` is undefined

src/shrpx.cc, src/shrpx_config.cc, src/shrpx_connection_handler.cc, src/shrpx_connection_handler.h, src/shrpx_quic.h, src/shrpx_worker.cc, src/shrpx_worker.h
Split thread into worker_process and thread.  Use thread to O(1) lookup for Worker.  This new machinery is not compatible to the previous version.  The old instance of nghttpx must not be upgraded with USR2 signal.  It should be restarted instead.
=> nghttpx: Split thread into worker_process and thread

doc/sources/nghttpx-howto.rst, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_quic.cc, src/shrpx_quic.h
Allocate 3 bits for QUIC configuration in Connection ID that matches the current QUIC LB draft.
=> nghttpx: Allocate 3 bits for QUIC configuration in Connection ID

lib/includes/nghttp2/nghttp2.h
=> Undefine NGHTTP2_NO_SSIZE_T if BUILDING_NGHTTP2 is defined

lib/nghttp2_submit.h
Fixes #2096 
I am not a fan of keeping supporting old generation of compilers, but this is a simple fix to achieve.
=> Suppress old compiler error

src/h2load.cc
Running a duration test over http/1.1 with connection close, will usually fail to complete. Eg: 
```
h2load -c50 -t1 -D10 --h1 --connect-to 10.10.0.148:4443 -H "Connection: close"  https://www.foo.com/0k.html
```
This is because there is a race condition between a client being terminated and it spawning a new connection. This patch prevents new clients being launched after entering the `DURATION_OVER` phase.
=> fix race condition on h1 connection close

lib/nghttp2_helper.h
This PR fixes the following `-Wextra-semi` errors in `nghttp2_helper.h` - seen when upgrading Electron to newer Node.js major version.
<details><summary>Details</summary>
<p>
```
../../third_party/electron_node/deps/nghttp2/lib/nghttp2_helper.h:41:30: error: extra ';' outside of a function [-Werror,-Wextra-semi]
41 | nghttp2_max_def(int8, int8_t);
|                              ^
../../third_party/electron_node/deps/nghttp2/lib/nghttp2_helper.h:42:32: error: extra ';' outside of a function [-Werror,-Wextra-semi]
42 | nghttp2_max_def(int16, int16_t);
|                                ^
../../third_party/electron_node/deps/nghttp2/lib/nghttp2_helper.h:43:32: error: extra ';' outside of a function [-Werror,-Wextra-semi]
43 | nghttp2_max_def(int32, int32_t);
|                                ^ …
```
=> fix: `-Wextra-semi` errors in `nghttp2_helper.h`

src/h2load.cc
If a connection is closing it returns -1 from on_read() and so the bytes in the last response are not counted in the stats.
=> account for bytes on closing connections

src/http2.cc, src/http2.h, src/nghttp.cc, src/nghttp.h
This change removes RFC 7540 priorities from nghttp.  nghttp now does not create the initial dependency tree.  --no-dep and --no-rfc7540-pri options have been removed.
nghttp now always sends NGHTTP2_SETTINGS_NO_RFC7540_PRIORITIES. --extpri option has been added to set priority for a given URI.
=> nghttp: Remove RFC 7540 priorities

src/HttpServer.cc, src/HttpServer.h, src/nghttpd.cc
This change deprecates --no-rfc7540-pri option.
SETTINGS_NO_RFC7540_PRIORITIES is now always sent.
=> nghttpd: Remove RFC 7540 priorities

lib/nghttp2_hd.c
Add bounds checking in hd_ringbuf_init() to prevent potential integer overflow during size calculations. While HPACK decoder controls its own buffer size (4-8K typical) and is not vulnerable to remote exploitation, this adds defensive programming guards for robustness.
=> fix: Add defensive bounds checking in hd_ringbuf_init()

src/shrpx.cc
Decrease DNS timeout to 250ms, which is the minimum duration allowed in c-ares.  The number of retries is 3, which is the default value of c-ares.
=> nghttpx: Tweak DNS timeout and retry

CMakeLists.txt
The CMake check for `GetTickCount64` on Windows only includes `<sysinfoapi.h>`.  If you check MSDN, it does say that `<sysinfoapi.h>` is the correct header, but it *also* says (include Windows.h).  Presently, the current check will fail 100% of the time because if you include sysinfoapi.h without including windows.h it's a compilation failure.  But if you do include windows.h, then it is not necessary to include sysinfoapi.h.
So the fix here is to simply change sysinfoapi.h to windows.h.  I confirmed after this patch that `HAVE_GETTICKCOUNT64` will be 1 on Windows, whereas before it would be undefined.
=> Fix CMake existence check for GetTickCount64

lib/nghttp2_session.c, lib/nghttp2_session.h, lib/nghttp2_submit.c, tests/nghttp2_session_test.c
Do not submit RST_STREAM more than once for a same stream with nghttp2_submit_rst_stream.  Historically, nghttp2_submit_rst_stream allows this.  nghttp2 also allows receiving multiple RST_STREAM frames.  To keep compatibility, nghttp2_submit_rst_stream does not fail if it attempts to submit RST_STREAM to already closed stream.
Fixes #2354
=> Do not submit RST_STREAM more than once

src/shrpx_config.h, src/shrpx_worker.cc
Instead of getnameinfo every time when forwarding a QUIC packet internally, cache binary representation of frontend address on startup, and compare them.
=> nghttpx: Rework frontend address resolution for QUIC packets

src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_quic_connection_handler.cc, src/shrpx_tls.cc
Previously, the value sent with Forward By parameter is the address assigned to the listening socket.  This does not work expected if the assigned address is wild card, (e.g., ::, 0.0.0.0).
This commit fixes this issue by using the local address that the connection is accepted.  For QUIC, it is the local address that handshake is performed, and it stays the same even after client address migration occurred.
=> nghttpx: Fix Forwarded By

src/allocator.h, src/app_helper.cc, src/base64.h, src/memchunk.h, src/shrpx_log.cc, src/shrpx_log.h, src/template.h, src/util.h
C array is sometimes very dangerous for this purpose, for example, if it contains NULL terminated string.  In such case, passing entire array is unacceptable.
=> Disallow array to substitute R &&

src/util.cc, src/util_test.cc
- Use std::chrono::system_clock::from_time_t
- Allocate extra byte for terminal NUL just in case
=> Amend date

third-party/Makefile.am
3.4.0 breaks out-of-tree build.  Fast forward to the commit that fixes it.
=> Bump mruby to 3.4.0+

src/h2load_http2_session.cc, src/memchunk.h
Make Memchunks::append return nothing because it always stores everything given.
=> Remove Memchunks::append return value

src/shrpx_https_upstream.cc, src/shrpx_log.cc, src/util.h
Remove NGHTTP2_MAX_UINT64_DIGITS.  Rely on
std::numeric_limits<T>::digits10 instead.
=> Remove NGHTTP2_MAX_UINT64_DIGITS

src/template.h
Without the change build against upcoming gcc-16 fails as:
template.h:457:9: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
457 |   const uint8_t, N == std::dynamic_extent ? std::dynamic_extent : N * sizeof(T)>
|         ^~~~~~~
=> src/template.h: add missing `cstdint` include

src/HttpServer.cc
Maybe relevant: https://github.com/nghttp2/nghttp2/pull/2119
=> nghttpd: Support SSLKEYLOGFILE

lib/nghttp2_submit.c
This change avoids [free(3)](https://man.openbsd.org/free.3) from stdlib in favor of `nghttp2_mem_free()` for freeing a buffer in an error path. The buffer is allocated with `nghttp2_mem_malloc()`.
=> Use allocator-aware free in failure path

src/base64.h, src/h2load.h, src/h2load_quic.h, src/shrpx.cc, src/shrpx_api_downstream_connection.cc, src/shrpx_client_handler.cc, src/shrpx_config.h, src/shrpx_https_upstream.cc, src/shrpx_memcached_connection.h, src/shrpx_process.h, src/shrpx_quic.cc, src/shrpx_quic.h, src/shrpx_signal.h, src/shrpx_tls.cc, src/shrpx_worker.h, src/tls.h, src/util.cc, src/util.h
- Use inline constexpr for constexpr variable with external linkage
- Use static constexpr where they should
- Use consteval for functions to generate a lookup table
=> src: constexpr fixup

src/h2load_quic.cc, src/shrpx_http3_upstream.cc
Adopt NGTCP2_WRITE_STREAM_FLAG_PADDING to increase opportunities for GSO.
=> src: Adopt NGTCP2_WRITE_STREAM_FLAG_PADDING

lib/nghttp2_session.c
Calling session_update_glitch_ratelim from
session_handle_invalid_stream2 makes handling error quite difficult because it might be called in nested function calls.  It seems to me that adding that is accidental.
=> Remove session_update_glitch_ratelim called from deep inside the chain

src/HttpServer.cc, src/HttpServer.h, src/nghttpd.cc
Use the same default list of groups as h2load.
See #2512
=> nghttpd: Make the supported groups configurable

examples/libevent-server.c, src/h2load.cc, src/shrpx_tls.cc
Replace SSL_CTX_set1_curves_list with SSL_CTX_set1_groups_list. Remove the workaround for wolfSSL because the bug has been fixed.
=> Use SSL_CTX_set1_groups_list

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_tls.cc
The groups option takes the list of the supported groups.  This deprecates ecdh-curves option.  If ecdh-curves option is used, it is treated as if groups option is specified.
See #2512
=> nghttpx: Add groups option

src/shrpx.cc, src/shrpx_tls.cc
We once refactored this with the shared curves, but it seems that it is not entirely correct for this.  Perhaps, the usage of X509_get_signature_nid was incorrect.
=> nghttpx: Select ECDSA cert based on EVP_PKEY_base_id

src/shrpx_tls.cc, src/shrpx_tls.h
Refactored the certificate selection to select the certificate in a single pass.  Cache the type of certificate to reduce the overhead.
=> nghttpx: Select a certificate in a single pass
