nghttp2/nghttp2

README.rst
=> Update README.rst with small text fixes

nghttpx.conf.sample
Just a minor fix to the sample configuration file.
=> Change --spdy-proxy to --http2-proxy

lib/Makefile.msvc
- source file list updated
- zlib removed
- build of .def files removed
=> Windows build fixes for #195

README.rst
some notes for building on windows under Mingw and Cygwin environment.
=> add notes for building on windows under Mingw and Cygwin

Dockerfile.android
I love your idea of cross-compiling Android nghttpx in Docker! I do not have to make my ubuntu host a mess now.
Docker will generate a new layer for every KEYWORD (RUN, WORKDIR, etc), so more keywords means more layers and slower DeviceCreate() processes. So I made some improvements to the Dockerfile, which will make it builds faster and more efficiently.
Hope you like it :-)
=> Improve Dockerfile

lib/nghttp2_int.h
=> fix comma at end of enumerator list [-Wpedantic]

src/asio_io_service_pool.cc, src/asio_io_service_pool.h, src/asio_server.cc, src/asio_server.h, src/asio_server_http2.cc, src/asio_server_http2_impl.cc, src/asio_server_http2_impl.h, src/includes/nghttp2/asio_http2_server.h
Make it possible to shutdown server gracefully and also joinable.
=> Graceful shutdown and joinable server

contrib/nghttpx.service
A service file for systemd distribution (Arch Linux, Ubuntu 15.04+, etc), much simpler than SysV init scripts. :-)
=> Add systemd service file

python/nghttp2.pyx
Client certificates can use used for authentication/authorization in the server,
so expose them similar to the remote address.
=> Expose client certificate, if available

src/nghttp.cc
It seems that HAR 1.2 does not have a proper representaion for pushed objects. I could´t just add a custom parameter so I think a comment at response will not hurt anybody.
=> Add comment on HAR on pushed objects

doc/sources/tutorial-client.rst
The overall meaning of the tutorial is the same. I added text describing frame types where it helps explain the callbacks better, e.g. introducing the HEADERS frame before on_header_callback().
Also fixed a couple of typos:
- Fixed ``reacb`` typo to ``readcb``
- Added parens to some functions, e.g. ``on_frame_recv_callback`` => ``on_frame_recv_callback()``
=> doc: Reword some of the client tutorial.

src/asio_server_tls_context.cc
same
https://github.com/tatsuhiro-t/nghttp2/commit/10f131c9d8f213422ac19218b227246e382328eb
=> Guard ecdh use with !OPENSSL_NO_EC @asio_server_tls_context.cc

contrib/nghttpx.service.in
Hi,
since now Type=forking is used, why not use PIDFile= too?
Tomasz
=> add PIDFile directive to systemd service

README.rst
So now we can run the same command on both system, add g++ requirement maybe kind of silly, I don't know. It's your call. :D
=> Update doc for Debian 7.0 or above and add g++ requirement

configure.ac, tests/Makefile.am
=> tests: fix broken linkage with --disable-static

contrib/nghttpx.service.in
This reverts commit 19c095a8172441690f30a21e70f73a0ec8475b2f.
See discussion at #375 for details.
=> Revert "add PIDFile directive to systemd service"

src/Makefile.am
Fix regression from bae37e3 breaking distcheck.
=> src/Makefile.am: fix missing allocator.h

src/shrpx_http_downstream_connection.cc, src/shrpx_http_downstream_connection.h
Finally got to the bottom of #563
=> nghttpx: Fix downstream connect callback called early

gennghttpxfun.py, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_hd.c, lib/nghttp2_hd.h, lib/nghttp2_option.c, lib/nghttp2_option.h, lib/nghttp2_session.c, src/HttpServer.cc, src/HttpServer.h, src/nghttp.cc, src/nghttp.h, src/nghttpd.cc, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_http2_session.cc, src/shrpx_http2_upstream.cc, tests/nghttp2_session_test.c
=> Set max deflate dynamic table size

doc/programmers-guide.rst, lib/nghttp2_http.c, src/shrpx_http_downstream_connection.cc, src/shrpx_mruby_module_response.cc, tests/nghttp2_session_test.c
=> Strict http framing

lib/nghttp2_http.c, lib/nghttp2_int.h, src/http2.cc, src/http2.h, src/shrpx_http_downstream_connection.cc, src/shrpx_mruby_module_response.cc, tests/nghttp2_session_test.c
=> Accept content-length: 0 in 204 response

.travis.yml, doc/Makefile.am
Run `make distcheck` for autotools build to verify tar ball integrity.
=> Travis make distcheck

src/shrpx_dns_resolver.cc
nghttpx DNS timeout related fix
=> Nghttpx dns timeout fix

src/shrpx_rate_limit.cc
=> nghttpx: Fix assertion error in libev ev_io_start

integration-tests/server_tester.go, src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_config.cc, src/shrpx_config.h
=> Nghttpx fronend proxyproto

examples/libevent-client.c, lib/nghttp2_hd.c, lib/nghttp2_submit.c
I have make a pass of PVS Studio (www.viva64.com) on nghttp2 and fix some issue reported (not found major issue...)
http://www.viva64.com/en/m/0036/
=> Fix issue reporting by PVS Studio

src/shrpx_log.cc
Write integer to log buffer directly to improve efficiency.  Remove
unused function templates.  Use [first, last) style arguments for
copy() function templates.
=> nghttpx: Efficient access.log writer

src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_config.cc, src/shrpx_https_upstream.cc
=> nghttpx: Enable backend pattern matching with http2-proxy

lib/nghttp2_session.c
This commit fixes the bug in nghttp2_session_want_write.  Previously,
it may return 0 if there is pending frames after GOAWAY frame is
submitted.
To avoid the situation that nghttp2_session_want_write keeps returning
nonzero after GOAWAY and the number of active streams is 0 (e.g., keep
receiving SETTINGS or PING), nghttp2_session_mem_recv now just
swallows the input data without parsing in this case.
Fixes #832
=> Fix nghttp2_session_want_write

src/asio_client_session_impl.cc, src/asio_client_session_impl.h
=> asio: client: Send PING after 30 seconds idle

src/shrpx.cc, src/shrpx_config.cc
=> nghttpx: Retry getaddrinfo without AI_ADDRCONFIG

src/asio_client_session_impl.cc
=> asio: Fix crash if connect takes longer time than ping interval

doc/sources/nghttpx-howto.rst, gennghttpxfun.py, integration-tests/nghttpx_http2_test.go, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_http2_downstream_connection.cc, src/shrpx_http_downstream_connection.cc
=> Nghttpx: Fix X-Forwarded-Proto handling

integration-tests/nghttpx_http2_test.go, src/shrpx_http_downstream_connection.cc
=> Nghttpx fix 204 handling

src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_config.cc, src/shrpx_config.h
=> nghttpx: SNI based backend server selection

src/shrpx_tls.cc
With this commit, SSL_TLSEXT_ERR_NOACK is returned from
servername_callback, which removes server_name extension from
ServerHello.  CertLookupTree is now used even if the number of server
certificate is one.  It is better to exercise it regularly.
=> nghttpx: Return SSL_TLSEXT_ERR_NOACK if server name is not recognized

third-party/build_config.rb
Fix compile error with mruby 1.3.0
=> Update mruby to 1.3.0

integration-tests/nghttpx_http2_test.go, src/shrpx_client_handler.cc, src/shrpx_client_handler.h
=> Fix bug that forwarded for is not affected by proxy protocol

src/h2load.cc, src/h2load.h
Reservoir sampling instead of systematic sampling
=> h2load: Reservoir sampling

src/h2load.cc
=> Fix bug that timing script stalls with -m1

src/h2load_http2_session.cc
=> h2load: Print out h2 header fields with --verbose option

src/allocator.h, src/asio_common.cc, src/memchunk.h, src/network.h, src/util.cc
Resolve #363 by introducing support for Windows/MinGW
=> Support for Windows / MinGW

doc/sources/tutorial-client.rst, examples/libevent-client.c, examples/libevent-server.c
=> examples: Make client and server work with libevent-2.1.8

integration-tests/nghttpx_http1_test.go, integration-tests/nghttpx_http2_test.go, integration-tests/server_tester.go, src/shrpx-unittest.cc, src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_downstream.cc, src/shrpx_downstream.h, src/shrpx_downstream_test.cc, src/shrpx_downstream_test.h, src/shrpx_http.cc, src/shrpx_http.h, src/shrpx_http2_upstream.cc, src/shrpx_http_downstream_connection.cc, src/shrpx_http_test.cc, src/shrpx_http_test.h, src/shrpx_https_upstream.cc, src/shrpx_worker.cc, src/shrpx_worker.h, src/util.cc, src/util.h
=> nghttpx: Cookie based session affinity

doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_callbacks.c, lib/nghttp2_callbacks.h, lib/nghttp2_helper.c, lib/nghttp2_session.c, src/HttpServer.cc, src/app_helper.cc, src/app_helper.h, src/nghttp.cc, src/shrpx_http2_upstream.cc
=> Error callback2

src/shrpx_client_handler.cc
This commit fixes the bug that ALPN validation does not occur when
ALPN list is not sent from client.
Fixes #1094
=> nghttpx: Fix missing ALPN validation (--npn-list)

lib/nghttp2_session.c
=> Allow PING frame to be sent after GOAWAY

doc/nghttpx.h2r, src/shrpx_mruby_module_env.cc, src/shrpx_tls.cc, src/shrpx_tls.h, src/util.cc, src/util.h
=> nghttpx: Add mruby tls_client_not_before, and tls_client_not_after

gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_tls.cc
=> nghttpx: Add an option to accept expired client certificate

src/util.cc
=> src: Define nghttp2_inet_pton wrapper to avoid inet_pton macro

doc/Makefile.am, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_session.c
=> Add nghttp2_session_set_user_data() public API function

src/asio_client_session_tls_impl.cc
=> asio: Support client side SNI

src/memchunk.h, src/shrpx_downstream.cc, src/shrpx_downstream.h, src/shrpx_http2_session.cc, src/shrpx_http2_upstream.cc, src/shrpx_http_downstream_connection.cc, src/shrpx_http_downstream_connection.h
=> Fix stream reset if data from client is arrived before dconn is attached

doc/nghttpx.h2r, gennghttpxfun.py, src/shrpx.cc, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_downstream.cc, src/shrpx_http2_upstream.cc, src/shrpx_https_upstream.cc, src/shrpx_worker.cc, src/shrpx_worker.h
An additional mruby script can be specified per backend using mruby parameter in -b option.
=> nghttpx: Support per-backend mruby script

genlibtokenlookup.py, lib/includes/nghttp2/nghttp2.h, lib/nghttp2_frame.c, lib/nghttp2_hd.c, lib/nghttp2_hd.h, lib/nghttp2_http.c, lib/nghttp2_http.h, lib/nghttp2_session.c, lib/nghttp2_session.h, lib/nghttp2_stream.h, tests/nghttp2_session_test.c
=> Implement RFC 8441

src/h2load_http1_session.cc
=> h2load: Handle HTTP/1 non-final response

src/CMakeLists.txt, src/Makefile.am, src/memchunk.h, src/priority_queue.h, src/priority_queue_test.cc, src/priority_queue_test.h, src/shrpx-unittest.cc, src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_client_handler.h, src/shrpx_config.cc, src/shrpx_config.h, src/shrpx_connect_blocker.cc, src/shrpx_http2_session.cc, src/shrpx_http2_session.h, src/shrpx_http2_upstream.cc, src/shrpx_http_downstream_connection.cc, src/shrpx_http_downstream_connection.h, src/shrpx_https_upstream.cc, src/shrpx_worker.cc, src/shrpx_worker.h, src/template.h
=> nghttpx: Backend address selection with weight

doc/sources/nghttpx-howto.rst, integration-tests/nghttpx_http2_test.go, integration-tests/server_tester.go, src/shrpx.cc, src/shrpx_client_handler.cc, src/shrpx_client_handler.h
=> nghttpx: Add PROXY protocol version 2

lib/Makefile.msvc
=> Added new nghttp2_ksl.c to Windows makefile

src/memchunk.h, src/shrpx_worker.cc
=> nghttpx: Make sure that Pool gets cleared when all buffers are returned

.github/workflows/build.yml, README.rst, configure.ac, docker/Dockerfile, src/h2load_quic.cc, src/shrpx_http3_upstream.cc
=> Bump ngtcp2

lib/nghttp2_net.h
=> add casts to silence implicit conversion warnings

src/http2.cc, src/http2_test.cc
Fix path component resolution when '.' is involved.
=> src: Fix path component resolution

integration-tests/nghttpx_http1_test.go, src/shrpx_https_upstream.cc
=> nghttpx: Fix bug that causes 400 response after upgrade failure

.github/workflows/build.yml, .github/workflows/fuzz.yml
=> Set workflow permissions

src/shrpx.cc
Fix heap-use-after-free introduced by
ddb667e8bff8fbdd1576f7637fc5d18bf5da9eb7.
=> nghttpx: Fix heap-use-after-free

cmakeconfig.h.in, configure.ac, src/util.h
Check libev availability, and guard the usage of libev in util.h.
=> Fix build error without libev

lib/nghttp2_session.c, tests/nghttp2_session_test.c
This commit fixes memory leak that happens when PUSH_PROMISE or HEADERS frame cannot be sent, and nghttp2_on_stream_close_callback fails with a fatal error.  For example, if GOAWAY frame has been received, a HEADERS frame that opens new stream cannot be sent.
This issue has already been made public via CVE-2023-35945 [1] issued by envoyproxy/envoy project.  During embargo period, the patch to fix this bug was accidentally submitted to nghttp2/nghttp2 repository [2]. And they decided to disclose CVE early.  I was notified just 1.5 hours before disclosure.  I had no time to respond.
PoC described in [1] is quite simple, but I think it is not enough to trigger this bug.  While it is true that receiving GOAWAY prevents a client from opening new stream, and nghttp2 enters error handling …
=> Fix memory leak

lib/nghttp2_time.c
=> Fix build error when both clock_gettime and GetTickCount64 are available

lib/nghttp2_time.c
=> Prefer clock_gettime if __CYGWIN__ defined

src/h2load.cc
=> h2load: Fix IPv6 address in :authority

src/h2load.cc, src/h2load.h
=> h2load: Add --sni option

.github/workflows/build.yml, docker/Dockerfile
Reduce commands by using `actions/checkout` with "`submodules: recursive`", also does the same for `git clone` commands.
=> Checkout with submodules

src/h2load.cc, src/nghttp.cc, src/tls.cc, src/tls.h
=> nghttp: Support SSLKEYLOGFILE

bpf/reuseport_kern.c
Drop QUIC packet if it is less than valid QUIC packet or it is coming from one of remote ports that are known to be a UDP service that can be used as a UDP reflection attack.
=> bpf: Drop bad QUIC packet

.github/workflows/build.yml, README.rst
Also bump boringssl so that it can be built without Go.
=> ci: Bump macos to 13

src/allocator.h
=> nghttpx: Fix alignment issues in BlockAllocator

src/http3.cc, src/http3.h, src/shrpx_http3_upstream.cc
http3::make_nv family functions are removed in favor of the new function.
=> Add http3::make_field family functions

lib/nghttp2_hd_huffman.c
=> Update the link for the Prefix.pdf document. fix #2178

.github/workflows/build.yml, integration-tests/setenv.in
Add dedicated distcheck buildtool parameter and run integration tests in autotool builds.
=> Add dedicated distcheck buildtool parameter

README.rst
=> Fix compiler versions in readme

cmake/FindLibcares.cmake
=> cmake: Fix c-ares v1.34.0 version detection failure

src/util.h
Adding QNX cross compilation support. Based on feedback from PR #2303
=> Add QNX Support

src/h2load_quic.cc, src/shrpx_http3_upstream.cc
=> Revert "quic: Use secure random generator for ngtcp2_rand"

src/h2load.cc, src/h2load.h, src/h2load_quic.cc
Refactor QUIC packet write path in h2load.  h2load now falls back to non-GSO write after GSO failed.
=> h2load: Refactor QUIC packet write path

src/shrpx_worker.cc
It seems that IP_PMTUDISC_PROBE works in some advertent situations.
=> src: Adopt IP_PMTUDISC_PROBE

src/shrpx_tls.cc
=> nghttpx: Prefer ML-DSA certificate over ECDSA

src/shrpx_tls.cc
Previously, the certificate selection in nghttpx depending on the supported signature algorithm is dedicated to OpenSSL.  This change brings the same capability to the BoringSSL build.  BoringSSL does not support ML-DSA certificate as of this writing.
=> nghttpx: Select certificate with BoringSSL

src/shrpx_tls.cc
Make servername_callback behavior consistent across all supported TLS stacks.  RFC 6066 does not provide any guidance or requirement when a server must not acknowledge Server Name Indication.
=> nghttpx: Make servername_callback behavior consistent
